### ISSUE TITLE
failed to find branch `staging`

### ISSUE THREAD

**Issue by mumu714** [HarukaMa/aleo-explorer-rust#1]
Unable to update https://github.com/AleoHQ/snarkVM.git?branch=staging

**Comment by HarukaMa** [comment]
refer to the first part of https://github.com/HarukaMa/aleo-explorer/issues/14#issuecomment-1761350208

**Comment by HarukaMa** [comment]
... but don't expect it's working right now

if you have time and people, you can always fix the missing parts yourselves though.
